export const refs = {
  registerForm: document.querySelector('.register-form'),
  registerEmail: document.querySelector('#register-email'),
  registerPassword: document.querySelector('#register-password'),
  registerBtn: document.querySelector('.register-button'),
  loginForm: document.querySelector('.login-form'),
  loginEmail: document.querySelector('#login-email'),
  loginPassword: document.querySelector('#login-password'),
  loginBtn: document.querySelector('.login-button'),
  logoutBtn: document.querySelector('.sign-out-button'),
  openModalBtn: document.querySelector('.auth-modal-open'),
  closeModalBtn: document.querySelector('.auth-modal-close'),
  modal: document.querySelector('.auth-modal-backdrop'),
  showLoginBtn: document.querySelector('.show-login'),
  showRegisterBtn: document.querySelector('.show-register'),
  loginForm: document.querySelector('.login-form-box'),
  registerForm: document.querySelector('.register-form-box'),
};
