import './sass/main.scss';
import './js/api';
import './js/test';
import './js/card_markup';
import './js/render_trends';
import './js/genre_info';
import './js/genres_data';
// ...
import './js/firebase/firebaseAuth';
import './js/firebase/signInModal';
import './js/search_film'
import './js/themse_picker'